export const STAGE_CSS = String.raw`
@font-face{font-family:Switzer;src:url('/fonts/switzer.woff2') format('woff2');font-display:swap}
@font-face{font-family:Cabinet;src:url('/fonts/cabinet-grotesk.woff2') format('woff2');font-display:swap}
@font-face{font-family:Commit;src:url('/fonts/commit-mono-400.woff2') format('woff2');font-display:swap}
:root{
  color-scheme:light;
  --paper:40 22% 98%;--raised:40 28% 99%;--warm:38 16% 94%;--sunk:40 14% 90%;
  --ink:30 10% 12%;--soft:30 9% 28%;--muted:30 8% 45%;--line:35 14% 84%;
  --accent:356 55% 30%;--contract:267 42% 49%;--code:210 58% 42%;--tests:138 42% 34%;
  --fixtures:34 52% 40%;--docs:324 40% 46%;--generated:192 38% 38%;--add:138 42% 34%;--del:2 48% 46%;
  --font:Switzer,system-ui,sans-serif;--display:Cabinet,Switzer,system-ui,sans-serif;
  --mono:Commit,ui-monospace,SFMono-Regular,Consolas,monospace;--pad:clamp(16px,2.5vw,40px);
  --left:250px;--right:248px;--gap:clamp(18px,2vw,34px)
}
:root[data-theme=dark]{
  color-scheme:dark;--paper:356 24% 11%;--raised:356 22% 13%;--warm:356 28% 8.5%;--sunk:356 32% 6.5%;
  --ink:20 20% 91%;--soft:16 14% 77%;--muted:8 9% 62%;--line:356 14% 23%;--accent:356 48% 66%;
  --contract:270 62% 72%;--code:205 75% 70%;--tests:138 55% 66%;--fixtures:35 72% 68%;--docs:324 62% 72%;
  --generated:190 58% 67%;--add:138 55% 66%;--del:2 70% 72%
}
*{box-sizing:border-box}
[hidden]{display:none!important}
html{background:hsl(var(--warm));scroll-behavior:smooth;-webkit-text-size-adjust:100%}
body{margin:0;background:hsl(var(--warm));color:hsl(var(--ink));font:15px/1.55 var(--font);overflow-x:hidden}
body:has(.focus-dialog[open]){overflow:hidden}
html:not(.js) [data-theme-toggle],html:not(.js) [data-focus-toggle],html:not(.js) [data-change-step],html:not(.js) [data-toggle-change],html:not(.js) [data-filter-unread],html:not(.js) [data-context-trigger],html:not(.js) [data-focus-panel-close]{display:none!important}html:not(.js) .file-context,html:not(.js) .hunk-gap{display:none}html:not(.js) .focus-left>header,html:not(.js) .focus-right>header{display:none}html:not(.js) .focus-left>nav,html:not(.js) .focus-ledger{height:100%}
a{color:hsl(var(--accent));text-decoration:underline;text-underline-offset:3px}
button,input{font:inherit}
button,a,summary{touch-action:manipulation}
button:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid hsl(var(--accent));outline-offset:3px}
code,pre{font-family:var(--mono)}
[data-category=Contract]{--category:hsl(var(--contract))}
[data-category=Code]{--category:hsl(var(--code))}
[data-category=Tests]{--category:hsl(var(--tests))}
[data-category='Test fixtures']{--category:hsl(var(--fixtures))}
[data-category=Docs]{--category:hsl(var(--docs))}
[data-category=Generated]{--category:hsl(var(--generated))}

.stage-shell{max-width:1800px;margin:auto;padding:0 var(--pad)}
.appbar{height:58px;display:flex;align-items:center;gap:20px;border-bottom:1px solid hsl(var(--line));font-size:13px}
.appbar .brand{display:flex;align-items:center;color:hsl(var(--ink));text-decoration:none;font:500 17px var(--display)}
.appbar .mark{width:25px;height:30px;margin-right:8px}.appnav{display:flex;gap:18px}
.appnav a{color:hsl(var(--muted));text-decoration:none}.appnav a[aria-current=page]{color:hsl(var(--ink))}
.bar-spacer{flex:1}.email-tag,.mono-id{font:11px var(--mono);color:hsl(var(--muted))}
.wsmenu{position:relative}.wsmenu summary{cursor:pointer;list-style:none;color:hsl(var(--soft))}
.wsmenu summary::-webkit-details-marker{display:none}.ws-chevron{width:8px;margin-left:7px}
.wsmenu-panel{position:absolute;right:0;top:30px;z-index:40;background:hsl(var(--paper));border:1px solid hsl(var(--line));padding:8px;min-width:210px;box-shadow:0 12px 30px #0003}
.wsmenu-panel a{display:block;padding:6px;color:hsl(var(--soft));text-decoration:none}.wsmenu-panel .mono-id{display:block}.wsmenu-sep{border-top:1px solid hsl(var(--line));margin:5px}
.theme-toggle,.icon-button{display:inline-grid;place-items:center;min-width:40px;min-height:40px;border:0;background:none;color:hsl(var(--muted));cursor:pointer;padding:8px}
.theme-toggle svg{width:15px;height:15px}.theme-toggle .tt-sun,.theme-toggle .tt-sys{display:none}
:root[data-theme=dark] .theme-toggle .tt-moon{display:none}:root[data-theme=dark] .theme-toggle .tt-sun{display:block}
:root[data-theme-mode=system] .theme-toggle .tt-moon,:root[data-theme-mode=system] .theme-toggle .tt-sun{display:none}:root[data-theme-mode=system] .theme-toggle .tt-sys{display:block}

.stage-grid{max-width:1800px;margin:auto;padding-left:var(--pad);padding-right:var(--pad);display:grid;grid-template-columns:var(--left) minmax(0,1fr) var(--right);column-gap:var(--gap)}
.stage-header{grid-column:2;padding:34px 0 25px}
.stage-context,.stage-source,.tree-summary,.tree-file,.hunk-range,.hunk-range,.terminal p{font:11px/1.45 var(--mono);color:hsl(var(--muted))}
.stage-header h1{font:300 clamp(30px,3.2vw,46px)/1.06 var(--display);letter-spacing:-.02em;margin:8px 0 15px;max-width:22ch}
.stage-source{display:flex;gap:8px 18px;flex-wrap:wrap}.stage-source span{overflow-wrap:anywhere}
.category-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(118px,1fr));margin-top:25px;border:1px solid hsl(var(--line));background:hsl(var(--raised))}
.category-summary>div{min-width:0;padding:10px 12px;border-right:1px solid hsl(var(--line));box-shadow:inset 0 2px var(--category)}
.category-summary>div:last-child{border-right:0}.category-summary>div>span:first-child{display:block;margin-bottom:5px;color:hsl(var(--soft));font-size:12px}
.attention-bar{min-height:46px;display:flex;align-items:center;gap:8px 18px;margin-top:15px;padding:7px 11px;border-left:3px solid hsl(var(--accent));border-block:1px solid hsl(var(--line));background:hsl(var(--accent)/.045);font-size:12px}
.attention-bar>span{color:hsl(var(--accent))}.attention-bar a{color:hsl(var(--muted));text-decoration:none}.attention-bar a:hover{text-decoration:underline}.attention-bar details{position:relative}.attention-bar details>summary{cursor:pointer;color:hsl(var(--muted));list-style:none}.attention-bar details>summary::-webkit-details-marker{display:none}.attention-bar details>div{position:absolute;z-index:20;top:24px;right:0;width:min(300px,80vw);padding:8px;border:1px solid hsl(var(--line));background:hsl(var(--paper));box-shadow:0 12px 30px #0003}.attention-bar details>div a{display:block;padding:5px}
.accounts{grid-column:2;display:block;padding:0 0 27px}.account{border-top:1px solid hsl(var(--line));min-width:0}.account>summary{padding:9px 0;list-style:none;cursor:pointer}.account>summary::-webkit-details-marker{display:none}.account h2{font:400 14px var(--font);margin:0 0 3px}.account h2 span{font:11px var(--mono);color:hsl(var(--muted));font-weight:400}.account>summary p{max-width:78ch;margin:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:hsl(var(--soft));font-size:13px}.account[open]>summary p{display:none}.account-full{max-width:78ch;padding:0 0 12px}.account-full h3{margin:12px 0 4px;font:400 13px var(--font)}.account .markdown>:first-child{margin-top:0}.account .markdown>:last-child{margin-bottom:0}
.stage-body{align-items:start;padding-top:5px;padding-bottom:100px}

.review-nav{grid-column:1;position:fixed;z-index:10;top:82px;left:max(var(--pad),calc((100vw - 1800px)/2 + var(--pad)));width:var(--left);min-width:0;max-height:calc(100vh - 96px);overflow:auto;padding-right:2px}
.mobile-nav-head{display:none}.review-nav-head{padding-bottom:14px;border-bottom:1px solid hsl(var(--line))}.review-nav-head>span,.review-nav-head>strong{display:block}.review-nav-head>span{font:11px var(--mono);color:hsl(var(--muted))}.review-nav-head>strong{margin:5px 0 9px;font:400 13px var(--font)}
.progress-track{display:block;height:2px;background:hsl(var(--line));overflow:hidden}.progress-track i{display:block;height:100%;background:hsl(var(--add));transition:width .18s}
.group-links a,.focus-group-link{--category:hsl(var(--code));display:grid;grid-template-columns:3px minmax(0,1fr) auto;align-items:center;gap:9px;min-height:57px;padding:8px 3px;border-bottom:1px solid hsl(var(--line));color:hsl(var(--ink));text-decoration:none}
.group-links a>i,.focus-group-link>i{width:3px;height:34px;background:var(--category)}
.group-links small,.group-links strong,.focus-group-link small,.focus-group-link strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.group-links small,.focus-group-link small{font:9px var(--mono);color:hsl(var(--muted));font-weight:400}.group-links strong,.focus-group-link strong{margin-top:2px;font:400 12px/1.25 var(--font)}
.group-links em,.focus-group-link em{font:9px var(--mono);font-style:normal;color:hsl(var(--muted))}.group-links a:hover,.focus-group-link:hover,.focus-group-link.is-active{background:hsl(var(--ink)/.045)}
.walkthrough{grid-column:2;min-width:0}.source-rail{grid-column:3;position:sticky;top:14px;color:hsl(var(--muted));font-size:13px}.source-rail h2{font:400 16px var(--display);margin:0 0 9px;color:hsl(var(--ink))}.source-rail p{margin:3px 0;overflow-wrap:anywhere}.source-rail section{border-top:1px solid hsl(var(--line));padding-top:10px;margin-top:17px}.source-rail code{display:block;margin-top:7px;font-size:11px}

.review-group-card{margin:0 0 22px;padding:18px;border:1px solid hsl(var(--line));background:hsl(var(--raised));scroll-margin-top:18px}
.group-head{--category:hsl(var(--code))}.group-sequence{display:flex;align-items:center;gap:8px;color:var(--category);font-size:11px}.group-sequence i{width:23px;height:2px;background:var(--category)}
.group-head h2{font:400 clamp(24px,2.4vw,31px)/1.12 var(--display);margin:8px 0 0}.group-copy{max-width:76ch;margin-top:10px;color:hsl(var(--soft))}.group-copy>p{margin:0}.group-copy>details{margin-top:7px}.group-copy summary,.focus-account summary{color:hsl(var(--muted));cursor:pointer;font-size:12px}.group-copy .markdown>:first-child,.focus-account .markdown>:first-child{margin-top:8px}.group-copy .markdown>:last-child,.focus-account .markdown>:last-child{margin-bottom:0}
.group-attention{margin:13px 0 0;padding:9px 11px;border-left:2px solid hsl(var(--accent));background:hsl(var(--accent)/.045);color:hsl(var(--soft));font-size:13px}
.group-points{margin:14px 0 0;padding:0;border-top:1px solid hsl(var(--line));list-style:none}.group-points li{display:grid;grid-template-columns:24px minmax(170px,35%) minmax(0,1fr);gap:8px;padding:8px 3px;border-bottom:1px solid hsl(var(--line))}.group-points li>span{font:9px var(--mono);color:hsl(var(--muted));padding-top:2px}.group-points code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.group-points p{max-width:76ch;margin:0;color:hsl(var(--soft));font-size:12px}.group-points .remaining p{color:hsl(var(--muted))}
.dimensions{display:flex;flex-wrap:wrap;align-items:center;gap:6px 22px}.dimensions.in-group{margin-top:11px}.dimension{display:inline-grid;grid-template-columns:30px minmax(0,1fr);align-items:center;gap:7px;color:hsl(var(--muted));font-size:11px;white-space:nowrap}
.signal-scale{width:30px;height:14px;display:flex;align-items:end;gap:3px}.signal-scale i{width:7px;height:4px;border:1px solid currentColor}.signal-scale i:nth-child(2){height:8px}.signal-scale i:nth-child(3){height:12px}.signal-scale i.active{background:currentColor}
.read-mark{width:30px;text-align:center;font-size:14px}.is-read .read-dimension{color:hsl(var(--add))}
.group-examples{margin:16px 0 0;padding:0;border-top:1px solid hsl(var(--line));list-style:none}.group-examples li{display:grid;grid-template-columns:minmax(180px,auto) minmax(0,1fr);gap:13px;padding:9px 3px;border-bottom:1px solid hsl(var(--line))}.group-examples code{font-size:11px;overflow-wrap:anywhere}.group-examples span{color:hsl(var(--muted));font-size:12px}
.group-preview{margin-top:17px;border:1px solid hsl(var(--line));background:hsl(var(--warm)/.65)}.group-preview-files{padding:7px 10px;border-bottom:1px solid hsl(var(--line))}.group-preview footer{min-height:50px;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:7px 8px 7px 11px;background:hsl(var(--raised))}.group-preview footer>span{font:11px var(--mono);color:hsl(var(--muted))}.review-group-action{min-height:36px;display:flex;align-items:center;gap:8px;padding:0 11px;border:1px solid hsl(var(--ink));border-radius:3px;background:hsl(var(--ink));color:hsl(var(--paper));font-size:12px;text-decoration:none}.review-group-action:hover{opacity:.86}

.tree-folder{margin:0}.tree-folder>summary{display:grid;grid-template-columns:12px minmax(0,1fr) auto;align-items:center;gap:6px;min-height:34px;list-style:none;cursor:pointer;color:hsl(var(--soft))}.tree-folder>summary::-webkit-details-marker{display:none}.tree-arrow{color:hsl(var(--muted));transition:transform .14s}.tree-folder[open]>summary .tree-arrow{transform:rotate(90deg)}.tree-folder[open]>summary>.tree-summary{display:none}.tree-children{margin-left:7px;padding-left:11px;border-left:1px solid hsl(var(--line))}
.tree-summary{display:flex;align-items:center;gap:10px;white-space:nowrap}.tree-summary>.diff-stat{font-size:10px}.tree-read{display:flex;align-items:center;gap:4px}.tree-read i{width:8px;height:8px;border:1px solid currentColor;border-radius:50%}.tree-read.is-read{color:hsl(var(--add))}.tree-read.is-read i{background:hsl(var(--add));border-color:hsl(var(--add))}
.tree-file{display:flex;align-items:center;gap:10px;min-height:35px;padding:4px 2px;color:hsl(var(--soft));text-decoration:none;min-width:0}.tree-file-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tree-file>.diff-stat{margin-left:auto}.tree-file:hover{background:hsl(var(--ink)/.04)}
.diff-stat{display:inline-flex;align-items:center;gap:7px;font:11px var(--mono);white-space:nowrap}.diff-add{color:hsl(var(--add))}.diff-del{color:hsl(var(--del))}
.group-materials{border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised))}.material-fact{border-top:1px solid hsl(var(--line))}.material-fact:first-child{border-top:0}.material-fact>summary{display:flex;justify-content:space-between;gap:15px;padding:10px 11px;list-style:none;cursor:pointer;font-size:12px}.material-fact>summary span:first-child{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.material-fact>summary span:last-child{font:10px var(--mono);color:hsl(var(--muted));white-space:nowrap}.material-fact>div{padding:0 11px 11px}.material-fact p{margin:5px 0}.fact-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:8px 18px;margin:10px 0 0}.fact-list dt{font:10px var(--mono);color:hsl(var(--muted))}.fact-list dd{margin:2px 0 0;font:11px var(--mono);overflow-wrap:anywhere}
.terminal{margin-top:34px;padding:18px 0 8px;border-top:1px solid hsl(var(--line));display:flex;justify-content:space-between;gap:20px;align-items:start}.terminal h2{font:400 20px var(--display);margin:0 0 10px}.terminal p{margin:0}
.mobile-bar,.page-scrim{display:none}

.focus-dialog{width:100vw;height:100dvh;max-width:none;max-height:none;margin:0;border:0;padding:0;background:hsl(var(--paper));color:hsl(var(--ink));overflow:hidden}
.focus-dialog[open]{position:fixed;inset:0;z-index:100}
.focus-dialog::backdrop{background:#0009}.focus-shell{height:100%;display:grid;grid-template-rows:58px minmax(0,1fr)}
.focus-header{display:grid;grid-template-columns:210px minmax(0,1fr) auto;align-items:center;border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised));min-width:0}
.focus-head-left{height:58px;display:flex;align-items:center;border-right:1px solid hsl(var(--line));min-width:0}.focus-brand{padding-left:16px;color:hsl(var(--ink));font:500 17px var(--display);text-decoration:none}.focus-head-left button{margin-left:auto}
.focus-head-left button,.focus-head-actions button,.focus-head-actions a{width:48px;height:57px;display:grid;place-items:center;border:0;border-left:1px solid hsl(var(--line));background:transparent;color:hsl(var(--muted));text-decoration:none;cursor:pointer}
.focus-head-title{min-width:0;padding:0 14px}.focus-head-title span,.focus-head-title strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.focus-head-title span{font:9px var(--mono);color:hsl(var(--muted))}.focus-head-title strong{margin-top:2px;font:400 13px var(--font)}
.focus-head-actions{height:58px;display:flex;align-items:center}.focus-head-actions>span{padding:0 13px;font:10px var(--mono);color:hsl(var(--muted))}.focus-head-actions a span{font-size:25px;line-height:1}
.focus-layout{position:relative;display:grid;grid-template-columns:210px minmax(0,1fr) 320px;min-height:0;overflow:hidden;transition:grid-template-columns .16s}
.focus-layout[data-left=closed]{grid-template-columns:48px minmax(0,1fr) 320px}.focus-layout[data-right=closed]{grid-template-columns:210px minmax(0,1fr) 48px}.focus-layout[data-left=closed][data-right=closed]{grid-template-columns:48px minmax(0,1fr) 48px}
.focus-left,.focus-right{height:100%;min-width:0;overflow:hidden;background:hsl(var(--raised))}.focus-left{border-right:1px solid hsl(var(--line))}.focus-right{border-left:1px solid hsl(var(--line))}
.focus-left>header,.focus-right>header{height:46px;display:flex;align-items:center;border-bottom:1px solid hsl(var(--line))}.focus-left>header{justify-content:flex-end}.focus-right>header{justify-content:space-between}.focus-left>header button,.focus-right>header button{height:45px;min-width:46px;padding:0 11px;border:0;background:none;color:hsl(var(--muted));cursor:pointer}.focus-right>header [data-filter-unread]{font-size:11px}.focus-right>header [data-filter-unread][aria-pressed=true]{color:hsl(var(--ink));box-shadow:inset 0 -2px hsl(var(--ink))}
.focus-left>nav{height:calc(100% - 46px);display:grid;grid-template-rows:minmax(116px,32%) minmax(0,1fr);overflow:hidden}.focus-ledger{height:calc(100% - 46px);overflow-y:auto;scrollbar-gutter:stable}.focus-group-links,.focus-file-tree{overflow-y:auto;scrollbar-gutter:stable}.focus-group-links{border-bottom:1px solid hsl(var(--line))}.focus-group-link{padding:6px 8px;min-height:49px}.focus-file-tree{padding:8px}.focus-tree-file{border-bottom:1px solid hsl(var(--line))}.focus-tree-file>.tree-file{font-size:10px}.tree-hunks{display:flex;flex-wrap:wrap;gap:2px;margin-left:18px;padding:1px 0 6px 8px;border-left:1px solid hsl(var(--line))}.tree-hunks a{min-width:36px;height:27px;display:flex;align-items:center;justify-content:center;gap:4px;padding:0 5px;color:hsl(var(--muted));font:9px var(--mono);text-decoration:none}.tree-hunks i{width:6px;height:6px;border:1px solid currentColor;border-radius:50%}.tree-hunks a[data-read=true] i{background:hsl(var(--add));border-color:hsl(var(--add))}.tree-hunks a.is-active{background:hsl(var(--ink)/.07);color:hsl(var(--ink))}
.focus-layout[data-left=closed] .focus-left>nav,.focus-layout[data-right=closed] .focus-right>header>*:first-child,.focus-layout[data-right=closed] .focus-ledger{display:none}.focus-layout[data-left=closed] .focus-left>header{justify-content:center}
.focus-stream{min-width:0;height:100%;overflow-y:auto;overflow-x:hidden;padding:0 12px 56px;background:hsl(var(--warm));scrollbar-gutter:stable}
.focus-stream-head{--category:hsl(var(--code));display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;padding:20px 2px 17px;max-width:1540px;margin:auto}.focus-stream-head>div>span{color:var(--category);font-size:11px}.focus-stream-head h2{font:400 27px/1.1 var(--display);margin:5px 0}.focus-stream-head>div>div{max-width:820px;color:hsl(var(--soft));font-size:13px}.focus-account>p{margin:0}.focus-account details{margin-top:6px}.focus-stream-head>div>div>:first-child{margin-top:0}.focus-stream-head>.diff-stat{padding-top:21px;font-size:13px}
.file-review{max-width:1540px;margin:0 auto 16px;border:1px solid hsl(var(--line));background:hsl(var(--raised));scroll-margin-top:4px}.file-review>summary{list-style:none;cursor:pointer}.file-review>summary::-webkit-details-marker{display:none}.file-review-head{position:sticky;top:0;z-index:7;min-height:50px;display:flex;align-items:center;gap:0;border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised)/.97);backdrop-filter:blur(12px)}.file-disclosure{width:39px;align-self:stretch;display:grid;place-items:center;border-right:1px solid hsl(var(--line));color:hsl(var(--muted));transition:transform .14s}.file-review:not([open]) .file-disclosure{transform:rotate(-90deg)}.file-review-title{min-width:0;flex:1;padding:6px 11px}.file-review-title strong,.file-review-title small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-review-title strong{font:11px var(--mono);font-weight:400}.file-review-title small{margin-top:3px;font:10px var(--font);color:hsl(var(--muted))}.file-review-head>.diff-stat{padding-right:13px}
.hunk-review{border-bottom:1px solid hsl(var(--line));background:hsl(var(--sunk));scroll-margin-top:52px}.hunk-review:last-child{border-bottom:0}.hunk-header{min-height:45px;display:flex;align-items:center;gap:9px;border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised));transition:background .12s,box-shadow .12s}.hunk-review.is-active .hunk-header,.hunk-review.is-linked-hover .hunk-header{box-shadow:inset 3px 0 hsl(var(--contract)/.55);background:hsl(var(--contract)/.045)}.hunk-review[data-collapsed=true] .hunk-header{border-bottom-color:transparent}.disclosure-button{width:39px;align-self:stretch;flex:none;border:0;border-right:1px solid hsl(var(--line));background:transparent;color:hsl(var(--muted));cursor:pointer}.hunk-review[data-collapsed=true] .disclosure-button span{display:inline-block;transform:rotate(-90deg)}.hunk-index{font:9px var(--mono);color:hsl(var(--muted))}.hunk-header>code{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.hunk-header>.diff-stat{flex:none}.dimensions.in-header{flex:none;gap:9px}.dimensions.in-header .dimension{grid-template-columns:26px}.dimensions.in-header .dimension>span:last-child{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}.dimensions.in-header .signal-scale,.dimensions.in-header .read-mark{width:26px}.hunk-body{min-width:0}.hunk-review[data-collapsed=true] .hunk-body{display:none}.hunk-description{margin:0;padding:11px 12px 0;background:hsl(var(--raised));color:hsl(var(--soft));font-size:12px}.hunk-range{margin:0;padding:5px 12px 10px;background:hsl(var(--raised));font:10px var(--mono);color:hsl(var(--muted))}
.read-form{display:flex;align-items:center;gap:7px}.read-form [data-read-failure]{font-size:10px;color:hsl(var(--del))}.read-form button{min-height:38px;border:0;background:none;color:hsl(var(--accent));padding:7px 10px;text-decoration:underline;text-underline-offset:3px;cursor:pointer;white-space:nowrap}.read-form button[disabled]{color:hsl(var(--muted));cursor:wait}.header-read{flex:none;margin-left:0;padding-right:3px}.header-read button{font-size:11px}
.hunk-gap{border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised))}.hunk-gap>button{width:100%;min-height:31px;border:0;background:transparent;color:hsl(var(--muted));font:9px var(--mono);cursor:pointer}.hunk-gap>button span{margin:0 10px}
.diff-frame{max-width:100%;overflow:auto;border-block:1px solid hsl(var(--line));background:hsl(var(--sunk));contain:inline-size}.diff{min-width:max-content;font:12px/1.62 var(--mono)}.hunk-range{position:sticky;left:0;padding:5px 10px;color:hsl(var(--muted));border-bottom:1px solid hsl(var(--line));background:hsl(var(--sunk));font:10px var(--mono)}.unified{padding:5px 0}.diff-line{display:grid;grid-template-columns:4.2em 4.2em 1.3em max-content;min-height:20px;white-space:pre}.diff-line.add{background:hsl(138 46% 45%/.17)}.diff-line.del{background:hsl(2 55% 48%/.17)}.line-old,.line-new{text-align:right;padding-right:7px;color:hsl(var(--muted));user-select:none}.line-mark{color:hsl(var(--muted));user-select:none}.line-code{padding-right:18px}.split{display:none;padding:5px 0}.split-head,.split-row{display:grid;grid-template-columns:minmax(560px,1fr) minmax(560px,1fr)}.split-head{position:sticky;left:0;color:hsl(var(--muted));border-bottom:1px solid hsl(var(--line));font:10px var(--mono)}.split-head span{padding:4px 10px}.split-cell{min-width:0;border-right:1px solid hsl(var(--line))}.split-cell:last-child{border:0}.split-cell .diff-line{grid-template-columns:4.2em 1.3em max-content}.split-cell .line-new{display:none}.split-cell.new .line-old{display:none}.split-cell.new .line-new{display:block}.diff-frame[data-layout=split] .unified{display:none}.diff-frame[data-layout=split] .split{display:block}
.file-context{border-top:1px solid hsl(var(--line));background:hsl(var(--raised));padding:4px 11px}.context-trigger{min-height:38px;border:0;background:none;color:hsl(var(--accent));padding:7px 0;text-decoration:underline;text-underline-offset:3px;cursor:pointer}.context-lines{max-height:360px;overflow:auto;background:hsl(var(--sunk));font:12px/1.6 var(--mono)}.context-line{display:grid;grid-template-columns:4em max-content;white-space:pre}.context-line span:first-child{text-align:right;padding-right:10px;color:hsl(var(--muted));user-select:none}
.focus-right .ledger-card{border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised));transition:background .12s,box-shadow .12s}.ledger-card.is-active,.ledger-card.is-linked-hover{background:hsl(var(--contract)/.045);box-shadow:inset 3px 0 hsl(var(--contract)/.55)}.ledger-card.is-filtered{display:none}.ledger-card>button{width:100%;min-height:43px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:7px;padding:6px 10px;border:0;background:none;text-align:left;cursor:pointer}.ledger-card>button>span{font:9px var(--mono);color:hsl(var(--muted))}.ledger-card>button code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:9px}.ledger-body{padding:9px 11px 11px;border-top:1px solid hsl(var(--line))}.dimensions.in-ledger{display:grid;gap:6px}.ledger-body p{margin:9px 0 0;color:hsl(var(--soft));font-size:12px}.ledger-read{justify-content:flex-end;margin-top:6px}.empty-ledger{padding:0 12px;color:hsl(var(--muted));font-size:12px}
.focus-scrim,.focus-mobile-bar{display:none}

@media(max-width:1150px){:root{--right:0px}.stage-grid{grid-template-columns:var(--left) minmax(0,1fr)}.stage-header,.accounts,.walkthrough{grid-column:2}.source-rail{display:none}.focus-layout{grid-template-columns:180px minmax(0,1fr) 286px}.focus-layout[data-left=closed]{grid-template-columns:48px minmax(0,1fr) 286px}.focus-layout[data-right=closed]{grid-template-columns:180px minmax(0,1fr) 48px}}
@media(max-width:760px){
  :root{--pad:16px}.appbar{gap:9px}.appnav,.email-tag{display:none}.wsmenu{margin-left:auto}.stage-grid{display:block}.stage-header{padding:22px 0 17px}.stage-header h1{font-size:32px}.category-summary{grid-template-columns:1fr 1fr;margin-top:20px}.category-summary>div:nth-child(even){border-right:0}.attention-bar{align-items:flex-start;flex-wrap:wrap;padding:9px 10px}.attention-bar>span{width:100%}.accounts{padding-bottom:20px}.stage-body{padding-top:0;padding-bottom:86px}.walkthrough{padding-top:22px}
  .review-nav{position:static;width:auto;max-height:none;margin-bottom:22px}.js .review-nav{position:fixed;z-index:70;inset:58px auto 0 0;width:min(88vw,330px);max-height:none;padding:18px 16px calc(20px + env(safe-area-inset-bottom));background:hsl(var(--paper));border-right:1px solid hsl(var(--line));transform:translateX(-104%);transition:transform .18s}.js .review-nav[data-open=true]{transform:none}.js .mobile-nav-head{display:flex;justify-content:flex-end}.mobile-nav-head button{min-height:40px;border:0;background:none;color:hsl(var(--accent));text-decoration:underline}.js .page-scrim{position:fixed;z-index:65;inset:58px 0 0;background:#0007;border:0;width:100%;height:100%;padding:0}.js .page-scrim[data-open=true]{display:block}
  .review-group-card{margin-inline:-1px;padding:14px}.group-head h2{font-size:26px}.group-points li{grid-template-columns:24px minmax(0,1fr)}.group-points code,.group-points p{grid-column:2}.group-examples li{display:block}.group-examples span{display:block;margin-top:3px}.group-preview{margin-inline:-1px}.group-preview-files{padding:7px}.tree-folder>summary{grid-template-columns:12px minmax(0,1fr)}.tree-folder>summary>.tree-summary{grid-column:2;justify-content:flex-start;padding-bottom:5px}.tree-file{flex-wrap:wrap;gap:5px 8px}.tree-file-name{flex:1 1 60%}.tree-file>.diff-stat{margin-left:0}.group-preview footer{min-height:58px}.review-group-action{min-height:44px}.material-fact>summary{display:grid}.material-fact>summary span:last-child{white-space:normal}.terminal{display:none}.js .mobile-bar{display:flex;position:fixed;z-index:60;left:0;right:0;bottom:0;align-items:center;justify-content:space-between;gap:10px;padding:10px 16px calc(10px + env(safe-area-inset-bottom));border-top:1px solid hsl(var(--line));background:hsl(var(--paper));font:12px var(--mono)}.mobile-bar button{min-height:44px;border:0;background:none;color:hsl(var(--accent));text-decoration:underline;padding:8px 0}
  .focus-shell{grid-template-rows:52px minmax(0,1fr) auto}.focus-header{grid-template-columns:48px minmax(0,1fr) auto}.focus-head-left{height:52px}.focus-brand{display:none}.focus-head-left button{width:48px;height:51px;margin:0;border-left:0}.focus-head-title{padding:0 8px}.focus-head-actions{height:52px}.focus-head-actions>span{display:none}.focus-head-actions button,.focus-head-actions a{width:46px;height:51px}.focus-head-actions [data-focus-toggle=detail]{display:none}.focus-layout,.focus-layout[data-left=closed],.focus-layout[data-right=closed],.focus-layout[data-left=closed][data-right=closed]{display:block;min-height:0}.focus-stream{width:100%;height:100%;padding:0 0 42px}.focus-stream-head{padding:17px 14px}.focus-stream-head h2{font-size:24px}.focus-stream-head>div>div{font-size:12px}.focus-stream-head>.diff-stat{padding-top:18px}.file-review{margin-bottom:14px;border-inline:0}.file-review-head{top:0}.file-review-title strong{font-size:10px}.hunk-header{flex-wrap:wrap;gap:7px;min-height:0;padding-bottom:8px}.disclosure-button{height:44px;align-self:flex-start}.hunk-index{padding-top:13px}.hunk-header>code{padding-top:12px}.hunk-header>.diff-stat{padding:12px 10px 0 0}.dimensions.in-header{order:5;flex:1 0 100%;display:grid;grid-template-columns:1fr 1fr 1fr;gap:5px 8px;padding:2px 11px 0}.dimensions.in-header .dimension{grid-template-columns:30px minmax(0,1fr);white-space:normal}.dimensions.in-header .dimension>span:last-child{position:static;width:auto;height:auto;clip-path:none}.dimensions.in-header .signal-scale,.dimensions.in-header .read-mark{width:30px}.header-read{order:6;width:100%;justify-content:flex-end;padding:0 3px}.header-read button{min-height:42px}.hunk-description{font-size:12px}.diff{font-size:11px}.split-head,.split-row{grid-template-columns:minmax(520px,1fr) minmax(520px,1fr)}
  .focus-left,.focus-right{position:absolute;z-index:20;top:0;height:100%;background:hsl(var(--raised));box-shadow:0 12px 30px #0005;transition:transform .16s}.focus-left{left:0;width:min(86vw,330px)}.focus-right{right:0;top:auto;bottom:0;width:100%;height:min(68%,610px);border-top:1px solid hsl(var(--line))}.js .focus-layout[data-panel=tree] .focus-left{transform:none}.js .focus-layout:not([data-panel=tree]) .focus-left{transform:translateX(-105%)}.js .focus-layout[data-panel=detail] .focus-right{transform:none}.js .focus-layout:not([data-panel=detail]) .focus-right{transform:translateY(105%)}.focus-layout[data-left=closed] .focus-left>nav,.focus-layout[data-right=closed] .focus-right>header>*:first-child,.focus-layout[data-right=closed] .focus-ledger{display:block}.js .focus-layout[data-panel=tree] .focus-scrim,.js .focus-layout[data-panel=detail] .focus-scrim{display:block;position:absolute;z-index:15;inset:0;width:100%;height:100%;border:0;background:#0007}.focus-mobile-bar{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 16px calc(8px + env(safe-area-inset-bottom));border-top:1px solid hsl(var(--line));background:hsl(var(--paper));font:11px var(--mono)}html:not(.js) .focus-layout{height:calc(100dvh - 52px);overflow:auto}html:not(.js) .focus-left{position:static;width:100%;height:auto;transform:none;box-shadow:none;border-bottom:1px solid hsl(var(--line))}html:not(.js) .focus-left>header,html:not(.js) .focus-right,html:not(.js) .focus-mobile-bar{display:none}html:not(.js) .focus-left>nav{height:auto;max-height:50vh}html:not(.js) .focus-stream{height:auto;overflow:visible}.focus-mobile-bar button{min-height:40px;border:0;background:none;color:hsl(var(--accent));text-decoration:underline}.focus-right .dimensions.in-ledger{grid-template-columns:1fr 1fr}.ledger-body p{font-size:13px}
}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.tree-arrow,.file-disclosure,.review-nav,.focus-layout,.focus-left,.focus-right,.progress-track i{transition:none}}
`;
