export const STAGE_CSS = String.raw`
@font-face{font-family:Switzer;src:url('/fonts/switzer.woff2') format('woff2');font-display:swap}
@font-face{font-family:Cabinet;src:url('/fonts/cabinet-grotesk.woff2') format('woff2');font-display:swap}
@font-face{font-family:Commit;src:url('/fonts/commit-mono-400.woff2') format('woff2');font-display:swap}
:root{
  color-scheme:light;
  --paper:40 22% 98%;--raised:40 28% 99%;--warm:38 16% 94%;--sunk:40 14% 90%;
  --ink:30 10% 12%;--soft:30 9% 28%;--muted:30 8% 39%;--line:35 14% 84%;
  --accent:356 55% 30%;--contract:267 42% 49%;--code:210 58% 42%;--tests:138 42% 34%;
  --fixtures:34 52% 40%;--docs:324 40% 46%;--generated:192 38% 38%;--add:138 42% 34%;--del:2 48% 46%;
  --font:Switzer,system-ui,sans-serif;--display:Cabinet,Switzer,system-ui,sans-serif;
  --mono:Commit,ui-monospace,SFMono-Regular,Consolas,monospace;--pad:clamp(16px,2.5vw,40px);
  --left:250px;--right:248px;--gap:clamp(18px,2vw,34px)
}
:root[data-theme=dark]{
  color-scheme:dark;--paper:356 24% 11%;--raised:356 22% 13%;--warm:356 28% 8.5%;--sunk:356 32% 6.5%;
  --ink:20 20% 91%;--soft:16 14% 77%;--muted:8 9% 62%;--line:356 14% 23%;--accent:356 48% 66%;
  --contract:270 62% 72%;--code:205 75% 70%;--tests:138 55% 66%;--fixtures:35 72% 68%;--docs:324 62% 72%;
  --generated:190 58% 67%;--add:138 55% 66%;--del:2 70% 72%
}
*{box-sizing:border-box}
[hidden]{display:none!important}
details:not([open])>:not(summary){display:none}
html{background:hsl(var(--warm));scroll-behavior:smooth;-webkit-text-size-adjust:100%}
body{margin:0;background:hsl(var(--warm));color:hsl(var(--ink));font:15px/1.55 var(--font);overflow-x:hidden}
body:has(.focus-dialog[open]){overflow:hidden}
html:not(.js) [data-theme-toggle],html:not(.js) [data-focus-toggle],html:not(.js) [data-change-step],html:not(.js) [data-toggle-change],html:not(.js) [data-filter-unread],html:not(.js) button[data-context-trigger],html:not(.js) [data-focus-panel-close]{display:none!important}html:not(.js) [data-context]:not([data-context-fallback]){display:none}html:not(.js) .focus-left>header,html:not(.js) .focus-right>header{display:none}html:not(.js) .focus-left>nav,html:not(.js) .focus-ledger{height:100%}
a{color:hsl(var(--accent));text-decoration:underline;text-underline-offset:3px}
button,input{font:inherit}
button,a,summary{touch-action:manipulation}
button:focus-visible,a:focus-visible,summary:focus-visible{outline:2px solid hsl(var(--accent));outline-offset:3px}
.disclosure-cue{display:inline-block;width:12px;flex:none;color:hsl(var(--muted));line-height:1;transition:transform .14s}
details[open]>summary .disclosure-cue{transform:rotate(90deg)}
code,pre{font-family:var(--mono)}
[data-category=Contract]{--category:hsl(var(--contract))}
[data-category=Code]{--category:hsl(var(--code))}
[data-category=Tests]{--category:hsl(var(--tests))}
[data-category='Test fixtures']{--category:hsl(var(--fixtures))}
[data-category=Docs]{--category:hsl(var(--docs))}
[data-category=Generated]{--category:hsl(var(--generated))}

.stage-shell{max-width:1800px;margin:auto;padding:0 var(--pad)}
.appbar{height:58px;display:flex;align-items:center;gap:20px;border-bottom:1px solid hsl(var(--line));font-size:13px}
.appbar .brand{display:flex;align-items:center;color:hsl(var(--ink));text-decoration:none;font:500 17px var(--display)}
.appbar .mark{width:25px;height:30px;margin-right:8px}.appnav{display:flex;gap:18px}
.appnav a{color:hsl(var(--muted));text-decoration:none}.appnav a[aria-current=page]{color:hsl(var(--ink))}
.bar-spacer{flex:1}.email-tag,.mono-id{font:11px var(--mono);color:hsl(var(--muted))}
.wsmenu{position:relative}.wsmenu summary{cursor:pointer;list-style:none;color:hsl(var(--soft))}
.wsmenu summary::-webkit-details-marker{display:none}.ws-chevron{width:8px;margin-left:7px}
.wsmenu-panel{position:absolute;right:0;top:30px;z-index:40;background:hsl(var(--paper));border:1px solid hsl(var(--line));padding:8px;min-width:210px;box-shadow:0 12px 30px #0003}
.wsmenu-panel a{display:block;padding:6px;color:hsl(var(--soft));text-decoration:none}.wsmenu-panel .mono-id{display:block}.wsmenu-sep{border-top:1px solid hsl(var(--line));margin:5px}
.theme-toggle,.icon-button{display:inline-grid;place-items:center;min-width:40px;min-height:40px;border:0;background:none;color:hsl(var(--muted));cursor:pointer;padding:8px}
.theme-toggle svg{width:15px;height:15px}.theme-toggle .tt-sun,.theme-toggle .tt-sys{display:none}
:root[data-theme=dark] .theme-toggle .tt-moon{display:none}:root[data-theme=dark] .theme-toggle .tt-sun{display:block}
:root[data-theme-mode=system] .theme-toggle .tt-moon,:root[data-theme-mode=system] .theme-toggle .tt-sun{display:none}:root[data-theme-mode=system] .theme-toggle .tt-sys{display:block}

.stage-grid{max-width:1800px;margin:auto;padding-left:var(--pad);padding-right:var(--pad);display:grid;grid-template-columns:var(--left) minmax(0,1fr) var(--right);column-gap:var(--gap)}
.stage-header{grid-column:2;padding:34px 0 25px}
.stage-context,.stage-source,.tree-summary,.tree-file,.hunk-range,.hunk-range,.terminal p{font:11px/1.45 var(--mono);color:hsl(var(--muted))}
.stage-header h1{font:300 clamp(30px,3.2vw,46px)/1.06 var(--display);letter-spacing:-.02em;margin:8px 0 15px;max-width:22ch}
.stage-source{display:flex;gap:8px 18px;flex-wrap:wrap}.stage-source span{overflow-wrap:anywhere}.stage-source .source-observation{flex-basis:100%}
.category-summary{display:grid;grid-template-columns:repeat(auto-fit,minmax(118px,1fr));margin-top:25px;border:1px solid hsl(var(--line));background:hsl(var(--raised))}
.category-summary>div{min-width:0;padding:10px 12px;border-right:1px solid hsl(var(--line));box-shadow:inset 0 2px var(--category)}
.category-summary>div:last-child{border-right:0}.category-summary>div>span:first-child{display:block;margin-bottom:5px;color:hsl(var(--soft));font-size:12px}
.attention-bar{min-height:46px;display:flex;align-items:center;gap:8px 18px;margin-top:15px;padding:7px 11px;border-left:3px solid hsl(var(--accent));border-block:1px solid hsl(var(--line));background:hsl(var(--accent)/.045);font-size:12px}
.attention-bar>span{color:hsl(var(--accent))}.attention-bar a{color:hsl(var(--muted));text-decoration:none}.attention-bar a:hover{text-decoration:underline}.attention-bar details{position:relative}.attention-bar details>summary{cursor:pointer;color:hsl(var(--muted));list-style:none}.attention-bar details>summary::-webkit-details-marker{display:none}.attention-bar details>div{position:absolute;z-index:20;top:24px;right:0;width:min(300px,80vw);padding:8px;border:1px solid hsl(var(--line));background:hsl(var(--paper));box-shadow:0 12px 30px #0003}.attention-bar details>div a{display:block;padding:5px}
.stage-workflow{margin:14px 0 0;font:11px var(--mono);color:hsl(var(--muted))}
.stage-workflow[data-witness-state=failed]{color:hsl(var(--accent))}
/* Newer source, and what this revision changed about the one before it. Same weight and
   type as the workflow line above them: three facts about the same source, one grammar. */
.stage-drift,.stage-movement{margin:6px 0 0;font:11px var(--mono);color:hsl(var(--muted))}
.stage-drift a{color:inherit;text-decoration:underline;text-underline-offset:2px}
/* The pull request reads as a link and nothing more: no pill, no colour of its own. */
.source-pr{color:inherit;text-decoration:underline;text-underline-offset:2px}.focus-pr-source{display:none}
/* A lineage whose capture has not finished. Same tokens as the header above it, so the
   shell is the review's own page early rather than a different kind of page. */
.capture-state{flex-basis:100%;margin:5px 0 0;font:400 18px var(--font);color:hsl(var(--soft))}.capture-state[data-capture-state=failed]{color:hsl(var(--accent))}
.pending-facts{grid-column:2;margin:0;padding:0 0 34px;display:grid;gap:7px;font:11px/1.5 var(--mono);color:hsl(var(--muted));max-width:78ch}
.pending-facts a{color:inherit}
.pending-facts strong{font-weight:400;color:hsl(var(--soft))}
.pending-facts form{margin:0}.pending-facts .capture-failure{margin:0;max-width:68ch;color:hsl(var(--soft));font:14px/1.5 var(--font)}
.capture-retry button{min-height:40px;border:1px solid hsl(var(--accent));border-radius:3px;background:hsl(var(--raised));color:hsl(var(--accent));padding:7px 11px;font:13px var(--font);cursor:pointer}
.focus-items{grid-column:2;display:block;padding:0 0 27px}
.focus-item{border-top:1px solid hsl(var(--line))}.focus-item>summary{display:grid;grid-template-columns:12px minmax(0,1fr) auto;align-items:baseline;gap:9px;padding:9px 0;list-style:none;cursor:pointer}.focus-item>summary::-webkit-details-marker{display:none}.focus-item h3{margin:0;font:400 14px var(--font)}.focus-item>summary>span:last-child{font:10px var(--mono);color:hsl(var(--muted));white-space:nowrap}
.focus-item-body{max-width:78ch;padding:0 0 13px;color:hsl(var(--soft));font-size:13px}.focus-item-body .markdown>:first-child{margin-top:0}.focus-item-body .markdown>:last-child{margin-bottom:0}
.focus-anchors{display:flex;flex-wrap:wrap;gap:5px 15px;margin:11px 0 0}.focus-anchors code{font-size:10px;overflow-wrap:anywhere}
.account-evidence{grid-column:2;padding:0 0 27px;border-top:1px solid hsl(var(--line))}.account-evidence h2{margin:9px 0 7px;font:400 14px var(--font)}.account-evidence ul{display:flex;flex-wrap:wrap;gap:6px 18px;margin:0;padding:0;list-style:none}.account-evidence li{display:flex;gap:7px;align-items:baseline;font-size:12px}.account-evidence li span{font:10px var(--mono);color:hsl(var(--muted))}
/* An account is read in full: the summary is the one sentence the witness wrote for the
   reader, and cutting it to a line would hide exactly what they came for. Only the
   builder's context, which is background, sits behind a disclosure. */
.accounts{grid-column:2;display:block;padding:0 0 27px}.account{border-top:1px solid hsl(var(--line));min-width:0;padding:9px 0 12px}.account h2{font:400 14px var(--font);margin:0 0 5px}.account h2 span{font:11px var(--mono);color:hsl(var(--muted));font-weight:400}.account-body{max-width:78ch;color:hsl(var(--soft));font-size:13px}.account-context{max-width:78ch;margin-top:8px}.account-context>summary{list-style:none;cursor:pointer;color:hsl(var(--muted));font-size:12px}.account-context>summary::-webkit-details-marker{display:none}.account-context>div{margin-top:6px;color:hsl(var(--soft));font-size:13px}.account .markdown>:first-child{margin-top:0}.account .markdown>:last-child{margin-bottom:0}
.stage-body{align-items:start;padding-top:5px;padding-bottom:100px}

.review-nav{grid-column:1;position:fixed;z-index:10;top:82px;left:max(var(--pad),calc((100vw - 1800px)/2 + var(--pad)));width:var(--left);min-width:0;max-height:calc(100vh - 96px);overflow:auto;padding-right:2px}
.mobile-nav-head{display:none}.review-nav-head{padding-bottom:14px;border-bottom:1px solid hsl(var(--line))}.review-nav-head>span,.review-nav-head>strong{display:block}.review-nav-head>span{font:11px var(--mono);color:hsl(var(--muted))}.review-nav-head>strong{margin:5px 0 9px;font:400 13px var(--font)}
.progress-track{display:block;height:2px;background:hsl(var(--line));overflow:hidden}.progress-track i{display:block;height:100%;background:hsl(var(--add));transition:width .18s}
.group-links a,.focus-group-link{--category:hsl(var(--code));display:grid;grid-template-columns:3px minmax(0,1fr) auto;align-items:center;gap:9px;min-height:57px;padding:8px 3px;border-bottom:1px solid hsl(var(--line));color:hsl(var(--ink));text-decoration:none}
.group-links a>i,.focus-group-link>i{width:3px;height:34px;background:var(--category)}
.group-links small,.group-links strong,.focus-group-link small,.focus-group-link strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.group-links small,.focus-group-link small{font:11px var(--mono);color:hsl(var(--muted));font-weight:400}.group-links strong,.focus-group-link strong{margin-top:2px;font:400 12px/1.25 var(--font)}
.group-links em,.focus-group-link em{font:9px var(--mono);font-style:normal;color:hsl(var(--muted))}.group-links a:hover,.focus-group-link:hover,.focus-group-link.is-active{background:hsl(var(--ink)/.045)}
.walkthrough{grid-column:2;min-width:0}.source-rail{grid-column:3;position:sticky;top:14px;color:hsl(var(--muted));font-size:13px}.source-rail h2{font:400 16px var(--display);margin:0 0 9px;color:hsl(var(--ink))}.source-rail p{margin:3px 0;overflow-wrap:anywhere}.source-rail section{border-top:1px solid hsl(var(--line));padding-top:10px;margin-top:17px}.source-rail code{display:block;margin-top:7px;font-size:11px}.mobile-detail-head{display:none}.source-rail [data-judgment-host] .judgment{margin-top:18px;padding-inline:0;border-bottom:0;background:transparent}

.review-group-card{margin:0 0 22px;padding:18px;border:1px solid hsl(var(--line));background:hsl(var(--raised));scroll-margin-top:18px}
.group-head{--category:hsl(var(--code))}.group-sequence{display:flex;align-items:center;gap:8px;color:var(--category);font-size:11px}.group-sequence i{width:23px;height:2px;background:var(--category)}
.group-head h2{font:400 clamp(24px,2.4vw,31px)/1.12 var(--display);margin:8px 0 0}
/* An evidence seam is navigation, not a title: its label is a path or a count, and the
   file list under it is the primary content, so it takes body type rather than display. */
.review-group-card[data-seam] .group-head h2{font:400 15px/1.4 var(--mono);margin-top:6px;overflow-wrap:anywhere}.group-copy{max-width:76ch;margin-top:10px;color:hsl(var(--soft))}.group-copy>p{margin:0}.group-copy>details{margin-top:7px}.group-copy summary,.focus-account summary{color:hsl(var(--muted));cursor:pointer;font-size:12px}.group-copy .markdown>:first-child,.focus-account .markdown>:first-child{margin-top:8px}.group-copy .markdown>:last-child,.focus-account .markdown>:last-child{margin-bottom:0}
.group-attention{margin:13px 0 0;padding:9px 11px;border-left:2px solid hsl(var(--accent));background:hsl(var(--accent)/.045);color:hsl(var(--soft));font-size:13px}
.group-points{margin:14px 0 0;padding:0;border-top:1px solid hsl(var(--line));list-style:none}.group-points li{display:grid;grid-template-columns:24px minmax(170px,35%) minmax(0,1fr);gap:8px;padding:8px 3px;border-bottom:1px solid hsl(var(--line))}.group-points li>span{font:9px var(--mono);color:hsl(var(--muted));padding-top:2px}.group-points code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.group-points p{max-width:76ch;margin:0;color:hsl(var(--soft));font-size:12px}.group-points .remaining p{color:hsl(var(--muted))}
.dimensions{display:flex;flex-wrap:wrap;align-items:center;gap:6px 22px}.dimensions.in-group{margin-top:11px}.dimension{display:inline-grid;grid-template-columns:30px minmax(0,1fr);align-items:center;gap:7px;color:hsl(var(--muted));font-size:11px;white-space:nowrap}
.signal-scale{width:30px;height:14px;display:flex;align-items:end;gap:3px}.signal-scale i{width:7px;height:4px;border:1px solid currentColor}.signal-scale i:nth-child(2){height:8px}.signal-scale i:nth-child(3){height:12px}.signal-scale i.active{background:currentColor}
.read-dimension{grid-template-columns:18px minmax(0,1fr);gap:4px}.read-mark{width:18px;text-align:center;font-size:14px}.is-read .read-dimension{color:hsl(var(--add))}
.group-examples{margin:16px 0 0;padding:0;border-top:1px solid hsl(var(--line));list-style:none}.group-examples li{display:grid;grid-template-columns:minmax(180px,auto) minmax(0,1fr);gap:13px;padding:9px 3px;border-bottom:1px solid hsl(var(--line))}.group-examples code{font-size:11px;overflow-wrap:anywhere}.group-examples span{color:hsl(var(--muted));font-size:12px}
.group-preview{margin-top:17px;border:1px solid hsl(var(--line));background:hsl(var(--warm)/.65)}.group-preview-files{padding:7px 10px;border-bottom:1px solid hsl(var(--line))}.group-preview footer{min-height:50px;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:7px 8px 7px 11px;background:hsl(var(--raised))}.group-preview footer>span{font:11px var(--mono);color:hsl(var(--muted))}.review-group-action{min-height:36px;display:flex;align-items:center;gap:8px;padding:0 11px;border:1px solid hsl(var(--ink));border-radius:3px;background:hsl(var(--ink));color:hsl(var(--paper));font-size:12px;text-decoration:none}.review-group-action:hover{opacity:.86}

.tree-folder{margin:0}.tree-folder>summary{display:grid;grid-template-columns:12px minmax(0,1fr) auto;align-items:center;gap:6px;min-height:34px;list-style:none;cursor:pointer;color:hsl(var(--soft))}.tree-folder>summary::-webkit-details-marker{display:none}.tree-folder[open]>summary>.tree-summary{display:none}.tree-label{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tree-children{margin-left:7px;padding-left:11px;border-left:1px solid hsl(var(--line))}
.tree-summary{display:flex;align-items:center;gap:10px;white-space:nowrap}.tree-summary>.diff-stat{font-size:10px}.tree-read{display:flex;align-items:center;gap:4px}.tree-read i{width:8px;height:8px;border:1px solid currentColor;border-radius:50%}.tree-read.is-read{color:hsl(var(--add))}.tree-read.is-read i{background:hsl(var(--add));border-color:hsl(var(--add))}
.tree-file{display:flex;align-items:center;gap:10px;min-height:35px;padding:4px 2px;color:hsl(var(--soft));text-decoration:none;min-width:0}.tree-file-name{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.tree-file>.diff-stat{margin-left:auto}.tree-file:hover{background:hsl(var(--ink)/.04)}
.diff-stat{display:inline-flex;align-items:center;gap:7px;font:11px var(--mono);white-space:nowrap}.diff-add{color:hsl(var(--add))}.diff-del{color:hsl(var(--del))}
.group-materials{border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised))}.material-fact{border-top:1px solid hsl(var(--line))}.material-fact:first-child{border-top:0}.material-fact>summary{display:grid;grid-template-columns:12px minmax(0,1fr) auto;align-items:baseline;gap:9px;padding:10px 11px;list-style:none;cursor:pointer;font-size:12px}.material-fact>summary::-webkit-details-marker{display:none}.material-fact>summary>span:nth-child(2){min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.material-fact>summary>.material-state{font:10px var(--mono);color:hsl(var(--muted));white-space:nowrap}.material-fact>summary [data-acknowledgement-summary]{color:hsl(var(--accent))}.material-fact>div{padding:0 11px 11px}.material-fact p{margin:5px 0}.fact-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(125px,1fr));gap:8px 18px;margin:10px 0 0}.fact-list dt{font:10px var(--mono);color:hsl(var(--muted))}.fact-list dd{margin:2px 0 0;font:11px var(--mono);overflow-wrap:anywhere}
.terminal{margin-top:34px;padding:18px 0 8px;border-top:1px solid hsl(var(--line));display:flex;justify-content:space-between;gap:20px;align-items:start}.terminal h2{font:400 20px var(--display);margin:0 0 10px}.terminal p{margin:0}
.mobile-bar,.page-scrim{display:none}

.focus-dialog{width:100vw;height:100dvh;max-width:none;max-height:none;margin:0;border:0;padding:0;background:hsl(var(--paper));color:hsl(var(--ink));overflow:hidden}
.focus-dialog[open]{position:fixed;inset:0;z-index:100}
.focus-dialog::backdrop{background:#0009}.focus-shell{height:100%;display:grid;grid-template-rows:58px minmax(0,1fr)}
.focus-header{display:grid;grid-template-columns:210px minmax(0,1fr) auto;align-items:center;border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised));min-width:0}
.focus-head-left{height:58px;display:flex;align-items:center;border-right:1px solid hsl(var(--line));min-width:0}.focus-brand{padding-left:16px;color:hsl(var(--ink));font:500 17px var(--display);text-decoration:none}.focus-head-left button{margin-left:auto}
.focus-head-left button,.focus-head-actions button,.focus-head-actions a{width:48px;height:57px;display:grid;place-items:center;border:0;border-left:1px solid hsl(var(--line));background:transparent;color:hsl(var(--muted));text-decoration:none;cursor:pointer}
.focus-head-title{min-width:0;padding:0 14px}.focus-head-title span,.focus-head-title strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.focus-head-title span{font:9px var(--mono);color:hsl(var(--muted))}.focus-head-title strong{margin-top:2px;font:400 13px var(--font)}
.focus-head-actions{height:58px;display:flex;align-items:center}.focus-head-actions>span{padding:0 13px;font:10px var(--mono);color:hsl(var(--muted))}.focus-head-actions a span{font-size:25px;line-height:1}
.focus-layout{position:relative;display:grid;grid-template-columns:210px minmax(0,1fr) 320px;min-height:0;overflow:hidden;transition:grid-template-columns .16s}
.focus-layout[data-left=closed]{grid-template-columns:48px minmax(0,1fr) 320px}.focus-layout[data-right=closed]{grid-template-columns:210px minmax(0,1fr) 48px}.focus-layout[data-left=closed][data-right=closed]{grid-template-columns:48px minmax(0,1fr) 48px}
.focus-left,.focus-right{height:100%;min-width:0;overflow:hidden;background:hsl(var(--raised))}.focus-left{border-right:1px solid hsl(var(--line))}.focus-right{border-left:1px solid hsl(var(--line))}
.focus-left>header,.focus-right>header{height:46px;display:flex;align-items:center;border-bottom:1px solid hsl(var(--line))}.focus-left>header{justify-content:flex-end}.focus-right>header{justify-content:space-between}.focus-left>header button,.focus-right>header button{height:45px;min-width:46px;padding:0 11px;border:0;background:none;color:hsl(var(--muted));cursor:pointer}.focus-right>header [data-filter-unread]{font-size:11px}.focus-right>header [data-filter-unread][aria-pressed=true]{color:hsl(var(--ink));box-shadow:inset 0 -2px hsl(var(--ink))}
.focus-left>nav{height:calc(100% - 46px);display:grid;grid-template-rows:minmax(116px,32%) minmax(0,1fr);overflow:hidden}.focus-ledger{height:calc(100% - 46px);overflow-y:auto;scrollbar-gutter:stable}.focus-group-links,.focus-file-tree{overflow-y:auto;scrollbar-gutter:stable}.focus-group-links{border-bottom:1px solid hsl(var(--line))}.focus-group-link{padding:6px 8px;min-height:49px}.focus-file-tree{padding:8px}.focus-tree-file{border-bottom:1px solid hsl(var(--line))}.focus-tree-file>.tree-file{font-size:10px}.tree-hunks{display:flex;flex-wrap:wrap;gap:2px;margin-left:18px;padding:1px 0 6px 8px;border-left:1px solid hsl(var(--line))}.tree-hunks a{min-width:36px;height:27px;display:flex;align-items:center;justify-content:center;gap:4px;padding:0 5px;color:hsl(var(--muted));font:9px var(--mono);text-decoration:none}.tree-hunks i{width:6px;height:6px;border:1px solid currentColor;border-radius:50%}.tree-hunks a[data-read=true] i{background:hsl(var(--add));border-color:hsl(var(--add))}.tree-hunks a.is-active{background:hsl(var(--ink)/.07);color:hsl(var(--ink))}
.focus-layout[data-left=closed] .focus-left>nav,.focus-layout[data-right=closed] .focus-right>header>*:first-child,.focus-layout[data-right=closed] .focus-ledger{display:none}.focus-layout[data-left=closed] .focus-left>header{justify-content:center}
.focus-stream{min-width:0;height:100%;overflow-y:auto;overflow-x:hidden;padding:0 12px 56px;background:hsl(var(--warm));scrollbar-gutter:stable}
.focus-stream-head{--category:hsl(var(--code));display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;padding:20px 2px 17px;max-width:1540px;margin:auto}.focus-stream-head>div>span{color:var(--category);font-size:11px}.focus-stream-head h2{font:400 27px/1.1 var(--display);margin:5px 0}.focus-stream-head>div>div{max-width:820px;color:hsl(var(--soft));font-size:13px}.focus-account>p{margin:0}.focus-account details{margin-top:6px}.focus-stream-head>div>div>:first-child{margin-top:0}.focus-stream-head>.diff-stat{padding-top:21px;font-size:13px}
.file-review{max-width:1540px;margin:0 auto 16px;border:1px solid hsl(var(--line));background:hsl(var(--raised));scroll-margin-top:4px}.file-review>summary{list-style:none;cursor:pointer}.file-review>summary::-webkit-details-marker{display:none}.file-review-head{position:sticky;top:0;z-index:7;min-height:50px;display:flex;align-items:center;gap:0;border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised)/.97);backdrop-filter:blur(12px)}.file-disclosure{width:39px;align-self:stretch;display:grid;place-items:center;border-right:1px solid hsl(var(--line))}.file-review-title{min-width:0;flex:1;padding:6px 11px}.file-review-title strong,.file-review-title small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-review-title strong{font:11px var(--mono);font-weight:400}.file-review-title small{margin-top:3px;font:10px var(--font);color:hsl(var(--muted))}.file-review-head>.diff-stat{padding-right:13px}
.hunk-review{border-bottom:1px solid hsl(var(--line));background:hsl(var(--sunk));scroll-margin-top:52px}.hunk-review:last-child{border-bottom:0}.hunk-header{min-height:45px;display:flex;align-items:center;gap:9px;border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised));transition:background .12s,box-shadow .12s}.hunk-review.is-active .hunk-header{box-shadow:inset 3px 0 hsl(var(--contract)/.55);background:hsl(var(--contract)/.045)}.hunk-review.is-linked-hover:not(.is-active) .hunk-header{box-shadow:none;background:hsl(var(--ink)/.035)}.hunk-review[data-collapsed=true] .hunk-header{border-bottom-color:transparent}.disclosure-button{width:39px;align-self:stretch;flex:none;border:0;border-right:1px solid hsl(var(--line));background:transparent;color:hsl(var(--muted));cursor:pointer}.hunk-review[data-collapsed=true] .disclosure-button span{display:inline-block;transform:rotate(-90deg)}.hunk-index{font:9px var(--mono);color:hsl(var(--muted))}.hunk-header>code{min-width:0;flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:10px}.hunk-header>.diff-stat{flex:none}.dimensions.in-header{flex:none;gap:9px}.dimensions.in-header .dimension:not(.read-dimension){grid-template-columns:26px}.dimensions.in-header .dimension:not(.read-dimension)>span:last-child{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%);white-space:nowrap}.dimensions.in-header .signal-scale{width:26px}.dimensions.in-header .read-dimension{grid-template-columns:18px auto;gap:4px}.hunk-body{min-width:0}.hunk-review[data-collapsed=true] .hunk-body{display:none}.hunk-description{margin:0;padding:11px 12px 0;background:hsl(var(--raised));color:hsl(var(--soft));font-size:12px}.hunk-range{margin:0;padding:5px 12px 10px;background:hsl(var(--raised));font:10px var(--mono);color:hsl(var(--muted))}
.read-form{display:flex;align-items:center;gap:7px}.read-form [data-read-failure]{font-size:10px;color:hsl(var(--del))}.read-form button{min-height:38px;border:0;background:none;color:hsl(var(--accent));padding:7px 10px;text-decoration:underline;text-underline-offset:3px;cursor:pointer;white-space:nowrap}.read-form button[disabled]{color:hsl(var(--muted));cursor:wait}.header-read{flex:none;margin-left:0;padding-right:3px}.header-read button{font-size:11px}
.hunk-gap{border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised))}.hunk-gap>button{width:100%;min-height:31px;border:0;background:transparent;color:hsl(var(--muted));font:9px var(--mono);cursor:pointer}.hunk-gap>button span{margin:0 10px}
.diff-frame{max-width:100%;overflow:auto;border-block:1px solid hsl(var(--line));background:hsl(var(--sunk));contain:inline-size}.diff{min-width:max-content;font:12px/1.62 var(--mono)}.hunk-range{position:sticky;left:0;padding:5px 10px;color:hsl(var(--muted));border-bottom:1px solid hsl(var(--line));background:hsl(var(--sunk));font:10px var(--mono)}.unified{padding:5px 0}.diff-line{display:grid;grid-template-columns:4.2em 4.2em 1.3em max-content;min-height:20px;white-space:pre}.diff-line.add{background:hsl(138 46% 45%/.17)}.diff-line.del{background:hsl(2 55% 48%/.17)}.line-old,.line-new{text-align:right;padding:0 7px 0 0;color:hsl(var(--muted));user-select:none;border:0;background:none;font:inherit;cursor:pointer;min-height:28px}.line-old[aria-pressed=true],.line-new[aria-pressed=true]{color:hsl(var(--ink));background:hsl(var(--accent)/.16)}.line-mark{color:hsl(var(--muted));user-select:none}.line-code{padding-right:18px}.split{display:none;padding:5px 0}.split-head,.split-row{display:grid;grid-template-columns:minmax(560px,1fr) minmax(560px,1fr)}.split-head{position:sticky;left:0;color:hsl(var(--muted));border-bottom:1px solid hsl(var(--line));font:10px var(--mono)}.split-head span{padding:4px 10px}.split-cell{min-width:0;border-right:1px solid hsl(var(--line))}.split-cell:last-child{border:0}.split-cell .diff-line{grid-template-columns:4.2em 1.3em max-content}.split-cell .line-new{display:none}.split-cell.new .line-old{display:none}.split-cell.new .line-new{display:block}.diff-frame[data-layout=split] .unified{display:none}.diff-frame[data-layout=split] .split{display:block}
.file-context{border-top:1px solid hsl(var(--line));background:hsl(var(--raised));padding:4px 11px}.context-trigger{min-height:38px;border:0;background:none;color:hsl(var(--accent));padding:7px 0;text-decoration:underline;text-underline-offset:3px;cursor:pointer}.context-lines{max-height:360px;overflow:auto;background:hsl(var(--sunk));font:12px/1.6 var(--mono)}.context-line{display:grid;grid-template-columns:4em max-content;white-space:pre}.context-line span:first-child{text-align:right;padding-right:10px;color:hsl(var(--muted));user-select:none}
.focus-right .ledger-card{border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised));transition:background .12s,box-shadow .12s}.ledger-card.is-active{background:hsl(var(--contract)/.045);box-shadow:inset 3px 0 hsl(var(--contract)/.55)}.ledger-card.is-linked-hover:not(.is-active){background:hsl(var(--ink)/.035);box-shadow:none}.ledger-card.is-filtered{display:none}.ledger-card>button{width:100%;min-height:43px;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:7px;padding:6px 10px;border:0;background:none;text-align:left;cursor:pointer}.ledger-card>button>span{font:9px var(--mono);color:hsl(var(--muted))}.ledger-card>button code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:9px}.ledger-body{padding:9px 11px 11px;border-top:1px solid hsl(var(--line))}.dimensions.in-ledger{display:grid;gap:6px}.ledger-body p{margin:9px 0 0;color:hsl(var(--soft));font-size:12px}.ledger-read{justify-content:flex-end;margin-top:6px}.empty-ledger{padding:0 12px;color:hsl(var(--muted));font-size:12px}
.focus-scrim,.focus-mobile-bar{display:none}

@media(max-width:1150px){:root{--right:0px}.stage-grid{grid-template-columns:var(--left) minmax(0,1fr)}.stage-header,.accounts,.focus-items,.account-evidence,.discussion,.walkthrough{grid-column:2}.source-rail{grid-column:2;position:static;margin-top:24px}.focus-layout{grid-template-columns:180px minmax(0,1fr) 286px}.focus-layout[data-left=closed]{grid-template-columns:48px minmax(0,1fr) 286px}.focus-layout[data-right=closed]{grid-template-columns:180px minmax(0,1fr) 48px}}
@media(max-width:760px){
  :root{--pad:16px}.appbar{gap:9px}.appnav,.email-tag{display:none}.wsmenu{margin-left:auto}.stage-grid{display:block}.stage-header{padding:22px 0 17px}.stage-header h1{font-size:32px}.stage-context .source-pr{display:inline-flex;align-items:center;min-height:44px;padding-inline:4px}.category-summary{grid-template-columns:1fr 1fr;margin-top:20px}.category-summary>div:nth-child(even){border-right:0}.attention-bar{align-items:flex-start;flex-wrap:wrap;padding:9px 10px}.attention-bar>span{width:100%}.accounts{padding-bottom:20px}.stage-body{padding-top:0;padding-bottom:86px}.walkthrough{padding-top:22px}
  .review-nav{position:static;width:auto;max-height:none;margin-bottom:22px}.js .review-nav{position:fixed;z-index:70;inset:58px auto 0 0;width:min(88vw,330px);max-height:none;padding:18px 16px calc(20px + env(safe-area-inset-bottom));background:hsl(var(--paper));border-right:1px solid hsl(var(--line));transform:translateX(-104%);transition:transform .18s}.js .review-nav[data-open=true]{transform:none}.js .mobile-nav-head,.js .mobile-detail-head{display:flex;justify-content:flex-end}.mobile-nav-head button,.mobile-detail-head button{min-height:40px;border:0;background:none;color:hsl(var(--accent));text-decoration:underline}.js .source-rail{display:block;position:fixed;z-index:70;inset:auto 0 0;height:min(76dvh,640px);margin:0;padding:14px 16px calc(24px + env(safe-area-inset-bottom));overflow-y:auto;background:hsl(var(--paper));border-top:1px solid hsl(var(--line));box-shadow:0 -12px 30px #0005;transform:translateY(104%);transition:transform .18s}.js .source-rail[data-open=true]{transform:none}html:not(.js) .source-rail{display:block;position:static;margin:24px 0 0;padding-top:16px;border-top:1px solid hsl(var(--line))}.js .page-scrim{position:fixed;z-index:65;inset:58px 0 0;background:#0007;border:0;width:100%;height:100%;padding:0}.js .page-scrim[data-open=true]{display:block}
  .review-group-card{margin-inline:-1px;padding:14px}.group-head h2{font-size:26px}.group-points li{grid-template-columns:24px minmax(0,1fr)}.group-points code,.group-points p{grid-column:2}.group-examples li{display:block}.group-examples span{display:block;margin-top:3px}.group-preview{margin-inline:-1px}.group-preview-files{padding:7px}.tree-folder>summary{grid-template-columns:12px minmax(0,1fr)}.tree-folder>summary>.tree-summary{grid-column:2;justify-content:flex-start;padding-bottom:5px}.tree-file{flex-wrap:wrap;gap:5px 8px}.tree-file-name{flex:1 1 60%}.tree-file>.diff-stat{margin-left:0}.group-preview footer{min-height:58px}.review-group-action{min-height:44px}.material-fact>summary{grid-template-columns:12px minmax(0,1fr)}.material-fact>summary>.material-state{grid-column:2;white-space:normal}.terminal{display:none}.js .mobile-bar{display:flex;position:fixed;z-index:60;left:0;right:0;bottom:0;align-items:center;justify-content:space-between;gap:10px;padding:10px 16px calc(10px + env(safe-area-inset-bottom));border-top:1px solid hsl(var(--line));background:hsl(var(--paper));font:12px var(--mono)}.mobile-bar button{min-height:44px;min-width:44px;border:0;background:none;color:hsl(var(--accent));text-decoration:underline;padding:8px 12px}.mobile-bar button:first-child{margin-left:-12px}.mobile-bar button:last-child{margin-right:-12px}
  .focus-shell{grid-template-rows:52px minmax(0,1fr) auto}.focus-header{grid-template-columns:48px minmax(0,1fr) auto}.focus-head-left{height:52px}.focus-brand{display:none}.focus-head-left button{width:48px;height:51px;margin:0;border-left:0}.focus-head-title{padding:0 8px}.focus-head-title>span{display:none}.focus-head-actions{height:52px}.focus-head-actions>span{display:none}.js .focus-head-actions>.source-pr{display:none}.focus-head-actions button,.focus-head-actions a{width:46px;height:51px}.focus-head-actions [data-focus-toggle=detail]{display:none}.focus-layout,.focus-layout[data-left=closed],.focus-layout[data-right=closed],.focus-layout[data-left=closed][data-right=closed]{display:block;min-height:0}.focus-stream{width:100%;height:100%;padding:0 0 42px}.focus-stream-head{padding:17px 14px}.focus-stream-head h2{font-size:24px}.focus-stream-head>div>div{font-size:12px}.focus-stream-head>.diff-stat{padding-top:18px}.file-review{margin-bottom:14px;border-inline:0}.file-review-head{top:0}.file-review-title strong{font-size:10px}.hunk-header{flex-wrap:wrap;gap:7px;min-height:0;padding-bottom:8px}.disclosure-button{height:44px;align-self:flex-start}.hunk-index{padding-top:13px}.hunk-header>code{padding-top:12px}.hunk-header>.diff-stat{padding:12px 10px 0 0}.dimensions.in-header{order:5;flex:1 0 100%;display:grid;grid-template-columns:1fr 1fr 1fr;gap:5px 8px;padding:2px 11px 0}.dimensions.in-header .dimension,.dimensions.in-header .dimension:not(.read-dimension){grid-template-columns:30px minmax(0,1fr);white-space:normal}.dimensions.in-header .dimension>span:last-child,.dimensions.in-header .dimension:not(.read-dimension)>span:last-child{position:static;width:auto;height:auto;clip-path:none;overflow:visible;white-space:normal}.dimensions.in-header .signal-scale{width:30px}.dimensions.in-header .read-dimension{grid-template-columns:18px minmax(0,1fr)}.header-read{order:6;width:100%;justify-content:flex-end;padding:0 3px}.header-read button{min-height:42px}.hunk-description{font-size:12px}.diff{font-size:11px}.split-head,.split-row{grid-template-columns:minmax(520px,1fr) minmax(520px,1fr)}
  .focus-left,.focus-right{position:absolute;z-index:20;top:0;height:100%;background:hsl(var(--raised));box-shadow:0 12px 30px #0005;transition:transform .16s}.focus-left{left:0;width:min(86vw,330px)}.focus-right{right:0;top:auto;bottom:0;width:100%;height:min(68%,610px);border-top:1px solid hsl(var(--line))}.js .focus-layout[data-panel=tree] .focus-left{transform:none}.js .focus-layout:not([data-panel=tree]) .focus-left{transform:translateX(-105%)}.js .focus-layout[data-panel=detail] .focus-right{transform:none}.js .focus-layout:not([data-panel=detail]) .focus-right{transform:translateY(105%)}.focus-layout[data-left=closed] .focus-left>nav,.focus-layout[data-right=closed] .focus-right>header>*:first-child,.focus-layout[data-right=closed] .focus-ledger{display:block}.js .focus-layout[data-panel=tree] .focus-scrim,.js .focus-layout[data-panel=detail] .focus-scrim{display:block;position:absolute;z-index:15;inset:0;width:100%;height:100%;border:0;background:#0007}.focus-mobile-bar{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px 16px calc(8px + env(safe-area-inset-bottom));border-top:1px solid hsl(var(--line));background:hsl(var(--paper));font:11px var(--mono)}html:not(.js) .focus-layout{height:calc(100dvh - 52px);overflow:auto}html:not(.js) .focus-left{position:static;width:100%;height:auto;transform:none;box-shadow:none;border-bottom:1px solid hsl(var(--line))}html:not(.js) .focus-left>header,html:not(.js) .focus-mobile-bar{display:none}html:not(.js) .focus-left>nav{height:auto;max-height:50vh}html:not(.js) .focus-stream{height:auto;overflow:visible}.focus-mobile-bar button{min-height:40px;border:0;background:none;color:hsl(var(--accent));text-decoration:underline}.focus-right .dimensions.in-ledger{grid-template-columns:1fr 1fr}.focus-pr-source{display:flex;align-items:center;min-height:52px;margin:0;padding:4px 14px;border-bottom:1px solid hsl(var(--line));font:11px var(--mono);color:hsl(var(--muted))}.focus-pr-source .source-pr{display:inline-flex;align-items:center;min-height:44px;padding-inline:4px}.ledger-body p{font-size:13px}
}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.disclosure-cue,.review-nav,.source-rail,.focus-layout,.focus-left,.focus-right,.progress-track i{transition:none}}

.focus-stream{--seam-h:0px}.focus-stream[data-seams]{--seam-h:34px}
.stack-layer{position:relative;display:flow-root}
.stack-seam{position:sticky;top:0;z-index:8;height:var(--seam-h);display:flex;align-items:center;gap:10px;padding:0 12px;max-width:1540px;margin:0 auto;background:hsl(var(--warm)/.97);backdrop-filter:blur(12px);border-bottom:1px solid hsl(var(--line));font:12px var(--font);color:hsl(var(--muted))}
.stack-seam b{font-weight:400;color:hsl(var(--ink));white-space:nowrap}.stack-seam span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.stack-seam a{margin-left:auto;color:inherit;text-decoration:underline;text-underline-offset:2px}
.focus-stream[data-seams] .file-review-head{top:var(--seam-h)}
.tree-layers{margin-left:6px;font:10px var(--mono);color:hsl(var(--muted));white-space:nowrap}.tree-layers.cross{color:hsl(var(--accent))}
.focus-subtitle{display:block;margin-top:2px;font:10px var(--mono);color:hsl(var(--muted));overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.scope-row{display:flex;align-items:center;gap:8px;margin:10px 0 0;font:11px var(--mono);color:hsl(var(--muted))}.scope-row label{display:inline-flex;align-items:center;gap:8px}.scope-select{max-width:100%;font:12px var(--font);color:hsl(var(--ink));background:hsl(var(--raised));border:1px solid hsl(var(--line));padding:5px 6px}.scope-go{font:11px var(--mono);border:1px solid hsl(var(--line));background:hsl(var(--raised));color:hsl(var(--ink));padding:4px 8px}.js .scope-go{display:none}
.focus-page{display:inline-flex;align-items:center;gap:2px;padding:0 6px;font:11px var(--mono);color:hsl(var(--muted));white-space:nowrap}.focus-page a{color:hsl(var(--ink));text-decoration:none;padding:0 5px;min-height:44px;display:inline-flex;align-items:center}.focus-page a[aria-disabled=true]{opacity:.35;pointer-events:none}
.ledger-page{margin:0;padding:9px 14px;border-bottom:1px solid hsl(var(--line));font:11px var(--mono);color:hsl(var(--muted))}
.stack-lines,.stack-members{grid-column:2}.stack-members{display:grid;gap:6px;margin:0 0 20px;padding:0;list-style:none}.stack-member{display:grid;grid-template-columns:28px minmax(0,1fr) auto;gap:12px;align-items:center;padding:10px 12px;border:1px solid hsl(var(--line));background:hsl(var(--raised));color:inherit;text-decoration:none}.stack-member>span:first-child{font:11px var(--mono);color:hsl(var(--muted))}.stack-member strong{display:block;font-weight:400;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.stack-member small{display:block;margin-top:2px;font:11px var(--mono);color:hsl(var(--muted));overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.stack-member .meter{width:120px;height:3px;background:hsl(var(--sunk))}.stack-member .meter i{display:block;height:100%;background:hsl(var(--accent))}.stack-member[data-status=removed]{opacity:.65}.stack-member[data-status=merged] strong::after{content:" · merged";color:hsl(var(--muted))}
.stack-lines{margin:0 0 20px}.stack-lines p{margin:4px 0 0}
.stack-fallback{max-width:1540px;margin:0 auto;padding:20px 2px;font-size:13px}.stack-fallback ol{padding-left:22px;font:12px var(--mono)}.stack-fallback li{margin:4px 0}.stack-fallback a{color:inherit}
.acknowledgement-form{display:flex;align-items:center;justify-content:flex-end;gap:9px;margin-top:9px;padding-top:7px;border-top:1px solid hsl(var(--line));font-size:11px}.acknowledgement-state{margin-right:auto;color:hsl(var(--muted))}.acknowledgement-form [role=status],.judgment-form [role=status]{color:hsl(var(--del))}.acknowledgement-form button{min-height:38px;border:0;background:none;color:hsl(var(--accent));padding:7px 0;text-decoration:underline;text-underline-offset:3px;cursor:pointer}
.judgment{padding:11px 12px 14px;border-bottom:1px solid hsl(var(--line));background:hsl(var(--raised))}.stage-overview>.judgment{grid-column:2;margin-bottom:28px;border-top:1px solid hsl(var(--line));background:transparent;padding-inline:0}.judgment h2{margin:0 0 7px;font:400 16px var(--display)}.judgment-required{margin:5px 0;color:hsl(var(--accent));font-size:12px}.judgment-blockers{margin:0;padding:0 0 7px;list-style:none;border-bottom:1px solid hsl(var(--line))}.judgment-blockers li{padding:4px 0;font:10px var(--mono);overflow-wrap:anywhere}.judgment-facts{margin:7px 0;font:10px var(--mono);color:hsl(var(--muted))}.judgment-error{margin:7px 0;color:hsl(var(--del));font-size:12px}.judgment-form{display:grid;gap:7px;padding:8px 0}.judgment-form label{display:grid;gap:4px;font-size:11px;color:hsl(var(--muted))}.judgment-form textarea{width:100%;min-height:74px;padding:7px;border:1px solid hsl(var(--line));background:hsl(var(--sunk));color:hsl(var(--ink));font:16px var(--font)}.judgment-form>div{display:flex;flex-wrap:wrap;gap:7px}.judgment-form button{min-height:40px;padding:6px 9px;border:1px solid hsl(var(--line));background:hsl(var(--raised));color:hsl(var(--ink))}.judgment-form button:disabled{border-color:hsl(var(--muted));background:hsl(var(--sunk));color:hsl(var(--muted));cursor:not-allowed}.judgment-row{padding:8px 0;border-top:1px solid hsl(var(--line))}.judgment-row>p{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:3px 8px;margin:0;font-size:11px}.judgment-row>p span:first-child{overflow-wrap:anywhere}.judgment-row>p span:nth-child(2){color:hsl(var(--accent))}.judgment-row time{grid-column:1/-1;color:hsl(var(--muted));font:9px var(--mono)}.judgment-comment{margin-top:6px;color:hsl(var(--soft));font-size:12px}.judgment-comment>:first-child{margin-top:0}.judgment-comment>:last-child{margin-bottom:0}
.github-projection{margin-top:18px;padding-top:12px;border-top:1px solid hsl(var(--line))}.github-projection h2{margin:0 0 8px;font:400 16px var(--display)}.github-inline{margin:5px 0;color:hsl(var(--muted));font-size:11px}.github-viewed-control,.github-viewed-retry,.github-submission-retry,.github-thread-publish,.github-thread-reply,.github-thread-resolution,.github-review-form{display:grid;gap:7px;margin-top:8px}.github-projection label,.github-thread-actions label{display:grid;gap:4px;color:hsl(var(--muted));font-size:11px}.github-projection select,.github-thread-actions select,.github-projection textarea,.github-thread-actions textarea{width:100%;min-width:0;padding:7px;border:1px solid hsl(var(--line));background:hsl(var(--sunk));color:hsl(var(--ink));font:16px var(--font)}.github-projection textarea,.github-thread-actions textarea{min-height:74px}.github-projection button,.github-thread-actions button{justify-self:start;min-height:40px;padding:6px 9px;border:1px solid hsl(var(--line));background:hsl(var(--raised));color:hsl(var(--ink));cursor:pointer}.github-projection button:disabled,.github-thread-actions button:disabled{color:hsl(var(--muted));cursor:wait}.github-viewed-states{margin:9px 0;padding:0;list-style:none}.github-viewed-states li{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:3px 9px;padding:6px 0;border-top:1px solid hsl(var(--line));font-size:10px}.github-viewed-states code{overflow-wrap:anywhere}.github-viewed-states span{color:hsl(var(--muted))}.github-viewed-states form{grid-column:1/-1;margin:0}.github-review-form{padding-top:10px;border-top:1px solid hsl(var(--line))}.github-review-form>div{display:grid;gap:7px}.github-local-comment{display:flex!important;align-items:center}.github-local-comment input{width:auto}.github-review-form blockquote{margin:0;padding:7px 9px;border-left:2px solid hsl(var(--line));color:hsl(var(--muted));font-size:11px;white-space:pre-wrap}.github-review-form [data-github-review-preview]{margin:0;padding:7px 9px;border:1px solid hsl(var(--line));background:hsl(var(--sunk));color:hsl(var(--soft));font:11px/1.5 var(--font);white-space:pre-wrap}.github-action-state{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:7px;color:hsl(var(--muted));font-size:10px}.github-action-state form{margin:0}.github-thread-actions{margin-top:9px;padding-top:8px;border-top:1px solid hsl(var(--line))}.github-thread-state{color:hsl(var(--muted));font-size:10px}.github-thread-actions [role=status],.github-projection [role=status]{color:hsl(var(--del));font-size:11px}
.document-share{margin-top:18px;border-top:1px solid hsl(var(--line));padding-top:12px}.document-share summary{display:flex;align-items:center;gap:6px;min-height:32px;list-style:none;cursor:pointer;color:hsl(var(--accent))}.document-share summary::-webkit-details-marker{display:none}.document-share summary>span:last-child{text-decoration:underline;text-underline-offset:3px}.document-share form{display:grid;gap:8px;margin-top:10px}.document-share label{display:grid;gap:4px;font:11px var(--mono);color:hsl(var(--muted))}.document-share input{min-width:0;padding:7px;border:1px solid hsl(var(--line));background:hsl(var(--raised));color:hsl(var(--ink));font:16px var(--font)}.document-share button{justify-self:start;padding:7px 9px;border:1px solid hsl(var(--line));background:hsl(var(--raised));color:hsl(var(--ink))}.document-share output input{width:100%;font:12px var(--mono)}
.discussion{grid-column:2;margin:4px 0 28px;padding-top:14px;border-top:1px solid hsl(var(--line))}.discussion h2{font:400 18px var(--display);margin:0 0 10px}.review-thread{border-top:1px solid hsl(var(--line));padding:9px 0}.thread-entry{padding:5px 0}.thread-entry>p{display:flex;align-items:baseline;gap:8px;margin:0 0 4px;font-size:11px;color:hsl(var(--muted))}.thread-entry time,.thread-entry a{margin-left:auto;color:inherit}.thread-entry .markdown{font-size:13px;color:hsl(var(--soft))}.thread-place,.conversation-state{font:11px var(--mono);color:hsl(var(--muted))}.thread-composer{margin-top:8px}.thread-composer>summary{min-height:38px;display:flex;align-items:center;gap:6px;list-style:none;color:hsl(var(--accent));cursor:pointer}.thread-composer>summary::-webkit-details-marker{display:none}.thread-new,.thread-reply,.thread-resolution,.conversation-refresh{display:grid;gap:6px;margin-top:8px}.thread-composer>.thread-new{margin-top:2px;padding:5px 0 8px}.thread-new label,.thread-reply label{display:grid;gap:4px;font-size:11px;color:hsl(var(--muted))}.thread-new textarea,.thread-reply textarea,.range-thread input,.range-thread select{width:100%;min-height:64px;padding:7px;border:1px solid hsl(var(--line));background:hsl(var(--paper));color:hsl(var(--ink));font:16px var(--font)}.range-thread input,.range-thread select{min-height:38px}.thread-new button,.thread-reply button,.thread-resolution button,.conversation-refresh button{justify-self:start;min-height:38px;padding:6px 9px;border:1px solid hsl(var(--line));background:hsl(var(--raised));color:hsl(var(--ink))}.thread-new [role=status] button{margin:5px 5px 0 0}.ledger-conversation{margin-top:9px;border-top:1px solid hsl(var(--line));padding-top:3px}.range-thread>summary,.earlier-discussion>summary{min-height:38px;display:flex;align-items:center;color:hsl(var(--accent));cursor:pointer}.focus-right .thread-new textarea,.focus-right .thread-reply textarea{background:hsl(var(--sunk))}html:not(.js) .focus-right{position:static;display:block;width:auto;height:auto;transform:none;box-shadow:none;border:0;border-top:1px solid hsl(var(--line))}html:not(.js) .focus-ledger{height:auto;overflow:visible}
@media(max-width:760px){.diff-line{min-height:36px}.line-old,.line-new{min-height:36px}.thread-composer>summary{min-height:44px}.github-projection button,.github-thread-actions button,.github-projection select,.github-thread-actions select{min-height:44px}.focus-head-title .focus-subtitle{display:none}.focus-head-actions .focus-page{display:none}.stack-seam{max-width:none;padding:0 14px}.stack-member .meter{display:none}.stack-member{grid-template-columns:24px minmax(0,1fr)}}
`;
